language: ruby
sudo: false
cache: bundler

dist: trusty

# Early warning system to catch if Rubygems breaks something
before_install:
  - gem update --system $(grep rubygems omnibus_overrides.rb | cut -d'"' -f2)
  - gem install bundler -v $(grep bundler omnibus_overrides.rb | cut -d'"' -f2)
  - rm -f .bundle/config

bundler_args: --without changelog development docgen guard maintenance omnibus_package tools aix bsd mac_os_x solaris windows --frozen

before_script:
 # force all .rspec tests into progress display to reduce line count
 - echo --color > .rspec
 - echo -fp >> .rspec
 # necessary for sudo: true tests, ingore failures on tests invoked with sudo: false
 - sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers || true
 - sudo apt-get -y install pv

# do not run expensive spec tests on PRs, only on branches
branches:
  only:
  - master
  - 10-stable
  - 11-stable

env:
  global:
    - FORCE_FFI_YAJL=ext

matrix:
  include:
  - rvm: 2.1
    sudo: true
    script: sudo /bin/bash ./ciphertest.sh
    # also remove integration / external tests
    bundler_args: --without changelog development docgen guard integration maintenance omnibus_package tools aix bsd mac_os_x solaris windows --frozen
